# Generated by Django 4.0.2 on 2022-05-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_editor', '0001_initial'),
        ('app_sticker_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=16)),
                ('telephone_number', models.CharField(max_length=32)),
                ('information_for_delivery', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('deliverydata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_order.deliverydata')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('PRINTED', 'Printed'), ('PACKAGED', 'Packaged'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received')], default='CREATED', max_length=16)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('app_order.deliverydata',),
        ),
        migrations.CreateModel(
            name='OrderStickerItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_order.orderitem')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_order.order')),
                ('sticker_style_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sticker_listing.stickerstyleoption')),
            ],
            bases=('app_order.orderitem',),
        ),
        migrations.CreateModel(
            name='OrderCanvasItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_order.orderitem')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('finished_canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_editor.finishedcanvas')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_order.order')),
            ],
            bases=('app_order.orderitem',),
        ),
    ]
