# Generated by Django 4.0.2 on 2022-05-14 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereditor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='finishedcanvas',
            name='canvas_style_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_editor.canvasstyleoption'),
        ),
        migrations.AddField(
            model_name='finishedcanvas',
            name='user_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_editor.usereditor'),
        ),
        migrations.AddField(
            model_name='canvasstyleoption',
            name='material_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_editor.canvasmaterialoption'),
        ),
        migrations.AddField(
            model_name='canvasstyleoption',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_editor.canvasstyle'),
        ),
        migrations.AddField(
            model_name='canvasstyle',
            name='canvas_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_editor.canvasmaterial'),
        ),
        migrations.AddField(
            model_name='canvasmaterialoption',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_editor.canvasmaterial'),
        ),
    ]
