# Generated by Django 4.0.2 on 2022-05-14 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cart_favorites', '0001_initial'),
        ('app_editor', '0001_initial'),
        ('app_sticker_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='stickerfavoriteitem',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cart_favorites.favorites'),
        ),
        migrations.AddField(
            model_name='stickerfavoriteitem',
            name='sticker_style_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sticker_listing.stickerstyleoption'),
        ),
        migrations.AddField(
            model_name='stickercartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cart_favorites.cart'),
        ),
        migrations.AddField(
            model_name='stickercartitem',
            name='sticker_style_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sticker_listing.stickerstyleoption'),
        ),
        migrations.AddField(
            model_name='canvascartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cart_favorites.cart'),
        ),
        migrations.AddField(
            model_name='canvascartitem',
            name='finished_canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_editor.finishedcanvas'),
        ),
    ]
