# Generated by Django 4.0.2 on 2022-05-14 18:44

import app_editor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_sticker_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasCutoutImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('active', models.BooleanField()),
                ('img_url', models.URLField()),
                ('auto_img_width', models.IntegerField(default=0)),
                ('auto_img_height', models.IntegerField(default=0)),
                ('auto_img_aspect_ratio_w_h', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasMaterial',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sticker_listing.material')),
            ],
            bases=('app_sticker_listing.material',),
        ),
        migrations.CreateModel(
            name='CanvasMaterialOption',
            fields=[
                ('materialoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sticker_listing.materialoption')),
            ],
            bases=('app_sticker_listing.materialoption',),
        ),
        migrations.CreateModel(
            name='CanvasStyle',
            fields=[
                ('style_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sticker_listing.style')),
            ],
            bases=('app_sticker_listing.style',),
        ),
        migrations.CreateModel(
            name='CanvasStyleOption',
            fields=[
                ('styleoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sticker_listing.styleoption')),
            ],
            bases=('app_sticker_listing.styleoption',),
        ),
        migrations.CreateModel(
            name='FinishedCanvas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
                ('background_color', models.CharField(default='123', max_length=7)),
                ('img_file', models.FileField(blank=True, upload_to=app_editor.models.img_file_path)),
                ('crop_img_file', models.FileField(blank=True, upload_to=app_editor.models.crop_img_file_path)),
                ('img_combi_file', models.FileField(blank=True, upload_to=app_editor.models.img_combi_file_path)),
                ('width_mm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('auto_img_width', models.IntegerField(default=0)),
                ('auto_img_height', models.IntegerField(default=0)),
                ('auto_img_aspect_ratio_w_h', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserEditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
