# Generated by Django 4.0.2 on 2022-05-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sticker_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerstyleoption',
            name='auto_longest_pick_limit_max',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stickerstyleoption',
            name='auto_longest_pick_limit_min',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
