# Generated by Django 4.0.2 on 2022-05-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sticker_listing', '0002_stickerstyleoption_auto_longest_pick_limit_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerstyleoption',
            name='auto_longest_pick_limit_max',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stickerstyleoption',
            name='auto_longest_pick_limit_min',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
